name: Deploy to Chrome web store
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          npm ci
          npm run build

      - name: Zip dist
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release.zip dist
