name: tutorial
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm install
      - name: Build project
        run: |
          pwd
          ls -al
          npm run build
